CREATE DATABASE DBMFSTUDIOS
GO

USE DBMFSTUDIOS
GO

---------------------TABLE-------------------------------------------------------
--- 1. PHANLOAI(MALOAI,TENLOAI)
GO
CREATE TABLE LOAITHIETBI
(	
	MALOAI VARCHAR(10)
	CONSTRAINT PK_PHANLOAI PRIMARY KEY (MALOAI),
	TENLOAI NVARCHAR(50) UNIQUE			-- BODY, Lens, Tản Sáng, Đèn, SoftBox, Gimbal, Flycam 
)

--- 1. THIET BI
GO
CREATE TABLE THIETBI
(
	MATB VARCHAR(10) PRIMARY KEY,
	TENTB NVARCHAR(35) NOT NULL,			--Mavic 2 pro // Phantom 4 // Sony A7R3 // 27-70 // 16-35 F1.5
	GIATRITB FLOAT NOT NULL,
	GIATHUE FLOAT NOT NULL, -- THUE THEO NGAY THEO TUNG THIET BI <500k ngay
	MALOAI VARCHAR(10) NOT NULL
	FOREIGN KEY (MALOAI) REFERENCES dbo.LOAITHIETBI(MALOAI)
)
-------- CHUCVU
GO
CREATE TABLE CHUCVU
(	
	MACV VARCHAR(10) 
	CONSTRAINT PK_CHUCVU PRIMARY KEY (MACV),
	TENCV NVARCHAR(50) UNIQUE
)

GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) CONSTRAINT NV_PK PRIMARY KEY,
	PASS VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(35) NOT NULL,
	GIOITINH BIT DEFAULT 0, --0 LA NU 1 LA NAM
	SDT VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	MACV VARCHAR(10) NOT NULL
	FOREIGN KEY (MACV) REFERENCES dbo.CHUCVU(MACV)
)
---4. KHACHHANG(MAKH,TENKH,DIACHI,DIENHOAI)
GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
	TENKH NVARCHAR(35) UNIQUE,
	DIACHI NVARCHAR(100) NOT NULL,
	SDT VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50),
)

GO
CREATE TABLE HOADON
(
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYTHUE DATE NOT NULL,
	NGAYHENTRA DATE NOT NULL,
	THONGTINDONHANG NVARCHAR(1000) NOT NULL,
	MAKH VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	MATB VARCHAR(10),
	TONGTIEN FLOAT NOT NULL,
	FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH),
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY (MATB) REFERENCES dbo.THIETBI(MATB)
)


--8 HOADON(MAHD,MAKH,MAMH,NGAYLAP,SOLUONG)

select * from KHACHHANG