CREATE DATABASE DBMFSTUDIOS
GO

USE DBMFSTUDIOS
GO

---------------------TABLE-------------------------------------------------------
--- 1. PHANLOAI(MALOAI,TENLOAI)
GO
CREATE TABLE LOAITHIETBI
(	
	MALOAI VARCHAR(10)
	CONSTRAINT PK_PHANLOAI PRIMARY KEY (MALOAI),
	TENLOAI NVARCHAR(50) UNIQUE
)

--- 1. THIET BI
GO
CREATE TABLE THIETBI
(
	MATB VARCHAR(10) PRIMARY KEY,
	TENTB NVARCHAR(35) NOT NULL,
	SOLUONG INT NOT NULL,
	MOTA NVARCHAR(50) NOT NULL,			-- HUHONG/MOI/SUACHUA/CU	CBB
	TINHTRANG NVARCHAR(50) NOT NULL,		-- DANG CHO THUE / CHUA CO KHACH THUE CBB
	GIATRITB FLOAT NOT NULL,
	GIATHUE FLOAT NOT NULL, -- THUE THEO NGAY THEO TUNG THIET BI
	MALOAI VARCHAR(10) NOT NULL
	FOREIGN KEY (MALOAI) REFERENCES dbo.LOAITHIETBI(MALOAI)
)
-------- CHUCVU
GO
CREATE TABLE CHUCVU
(	
	MACV VARCHAR(10) 
	CONSTRAINT PK_CHUCVU PRIMARY KEY (MACV),
	TENCV NVARCHAR(50) UNIQUE
)
Select HOTEN,  MACV from NHANVIEN where MaNV = 'NV2201'
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) CONSTRAINT NV_PK PRIMARY KEY,
	PASS VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(35) NOT NULL,
	GIOITINH BIT DEFAULT 0, --0 LA NU 1 LA NAM
	SDT VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	MACV VARCHAR(10) NOT NULL
	FOREIGN KEY (MACV) REFERENCES dbo.CHUCVU(MACV)
)
---4. KHACHHANG(MAKH,TENKH,DIACHI,DIENHOAI)
GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
	TENKH NVARCHAR(35) UNIQUE,
	DIACHI NVARCHAR(100) NOT NULL,
	SDT VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50),
)

GO
CREATE TABLE PHIEUTHUETHIETBI
(
	MAPTHUE VARCHAR(10) PRIMARY KEY,
	SOLUONG INT NOT NULL CONSTRAINT CK_SLTB CHECK(SOLUONG >0),
	NGAYTHUE DATE NOT NULL,
	NGAYHENTRA DATE NOT NULL,
	TIENCOC FLOAT NOT NULL CHECK (TIENCOC>0),
	MAKH VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	MATB VARCHAR(10) NOT NULL

	FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH),
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY (MATB) REFERENCES dbo.THIETBI(MATB)
)


--8 HOADON(MAHD,MAKH,MAMH,NGAYLAP,SOLUONG)
GO
CREATE TABLE HOADON
(
	MAHD VARCHAR(10)
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
	MAKH VARCHAR(10)
	CONSTRAINT FK_HD_MAKH REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE ON UPDATE CASCADE,
	MATB VARCHAR(10) 
	CONSTRAINT FK_HD_MATB REFERENCES THIETBI(MATB) ON DELETE CASCADE ON UPDATE CASCADE,
	NGAYLAP DATETIME,
	TONGTIEN FLOAT NOT NULL,
)

--CHI TIET HOA DON
GO
CREATE TABLE CT_HOADON
(
SOHD VARCHAR(10) NOT NULL foreign key references HOADON(MAHD),
MATB  VARCHAR(10) NOT NULL foreign key references THIETBI(MATB),
CONSTRAINT  PK_MA PRIMARY KEY(SOHD,MATB),
NGAYTHUE DATETIME NOT NULL,
NGAYTRA DATETIME NOT NULL,
GIATHUE FLOAT NOT NULL,
SOLUONG INT NOT NULL,
)



--CREATE TABLE DB_USER
--(
--	USERNAME VARCHAR(30) 
--	CONSTRAINT PK_DTUSER PRIMARY KEY(USERNAME),
--	PASS VARCHAR(30) NOT NULL,
--	USERTYPE NVARCHAR(50) NOT NULL,	
--)
--select *from DB_USER
--go
--CREATE PROC PROC_INSERT_DBUSER @USER VARCHAR(30),@PASS NVARCHAR(30),@QUYEN  NVARCHAR(50)
--AS 
--  insert into DB_USER values (@USER,@PASS,@QUYEN)

---- RANG BUOC----
----STORED PROCEDURE : INSERT, UPDATE, DELETE
-----------1.KHACHHANG-------------

GO
CREATE PROC PROC_INSERT_KHACHHANG @MAKH VARCHAR(10),@TENKH NVARCHAR(35),@DIACHI NVARCHAR(100),@SDT VARCHAR(15), @EMAIL VARCHAR(50)
AS 
  INSERT INTO KHACHHANG VALUES(@MAKH,@TENKH,@DIACHI,@SDT, @EMAIL) 
---------  
GO
CREATE PROC PROC_UPDATE_KHACHHANG @MAKH VARCHAR(10),@TENKH NVARCHAR(35),@DIACHI NVARCHAR(100),@SDT VARCHAR(15), @EMAIL VARCHAR(50)
AS 
  UPDATE KHACHHANG SET TENKH =@TENKH, DIACHI =@DIACHI,SDT = @SDT, EMAIL = @EMAIL WHERE  MAKH =@MAKH
---------
GO

CREATE PROC PROC_DELETE_KHACHHANG @MAKH VARCHAR(10)
AS 
  DELETE KHACHHANG WHERE MAKH = @MAKH


-----------2.NHANVIEN-------------

GO
CREATE PROC PROC_INSERT_NHANVIEN @MANV VARCHAR(10),@PASS VARCHAR(50),@HOTEN NVARCHAR(35),@GIOITINH BIT,@SDT VARCHAR(15),@CHUCVU NVARCHAR(50) , @EMAIL VARCHAR(50)
AS 
  INSERT INTO NHANVIEN VALUES(@MANV,@PASS,@HOTEN,@GIOITINH,@SDT,@CHUCVU, @EMAIL) 
---------  
GO
CREATE PROC PROC_UPDATE_NHANVIEN @MANV VARCHAR(10),@PASS VARCHAR(50),@HOTEN NVARCHAR(35),@GIOITINH BIT,@SDT VARCHAR(15),@CHUCVU NVARCHAR(50) , @EMAIL VARCHAR(50)
AS 
  UPDATE NHANVIEN SET PASS = @PASS, HOTEN =@HOTEN, GIOITINH =@GIOITINH,SDT = @SDT, CHUCVU = @CHUCVU, EMAIL = @EMAIL WHERE  MANV =@MANV
---------
GO

CREATE PROC PROC_DELETE_NHANVIEN @MANV VARCHAR(10)
AS 
  DELETE NHANVIEN WHERE MANV = @MANV

-----------3.LOAITHIETBI-------------
GO
CREATE PROC PROC_INSERT_PHANLOAI @MALOAI VARCHAR(10),@TENLOAI NVARCHAR(100)
AS 
  INSERT INTO LOAITHIETBI VALUES(@MALOAI,@TENLOAI) 
---------  
GO
CREATE PROC PROC_UPDATE_PHANLOAI @MALOAI VARCHAR(10),@TENLOAI NVARCHAR(100)
AS 
  UPDATE LOAITHIETBI SET TENLOAI = @TENLOAI WHERE MALOAI =@MALOAI
---------
GO
CREATE PROC PROC_DELETE_PHANLOAI @MALOAI VARCHAR(10)
AS 
  DELETE LOAITHIETBI WHERE MALOAI =@MALOAI

-----------4.THIETBI-------------

GO
CREATE PROC PROC_INSERT_THIETBI @MATB VARCHAR(10),@TENTB NVARCHAR(50), @SOLUONG INT, @MOTA NVARCHAR(50), @TINHTRANG NVARCHAR(50), @GIATRITB FLOAT, @GIATHUE FLOAT, @MALOAI VARCHAR(10)
AS 
  INSERT INTO THIETBI VALUES(@MATB, @TENTB, @SOLUONG, @MOTA, @TINHTRANG, @GIATRITB, @GIATHUE, @MALOAI) 
---------  
GO
CREATE PROC PROC_UPDATE_THIETBI @MATB VARCHAR(10),@TENTB NVARCHAR(50), @SOLUONG INT, @MOTA NVARCHAR(50), @TINHTRANG NVARCHAR(50), @GIATRITB FLOAT, @GIATHUE FLOAT, @MALOAI VARCHAR(10)
AS 
  UPDATE THIETBI SET TENTB=@TENTB, SOLUONG=@SOLUONG, MOTA=@MOTA, TINHTRANG = @TINHTRANG, GIATRITB = @GIATRITB, GIATHUE = @GIATHUE, MALOAI = @MALOAI WHERE  MATB =@MATB
---------
GO
CREATE PROC PROC_DELETE_THIETBI @MATB VARCHAR(10)
AS 
  DELETE THIETBI WHERE MATB = @MATB
  
  -----------5.HOADON-------------


GO
CREATE PROC PROC_INSERT_HOADON @MAHD VARCHAR(10),@MAKH VARCHAR(10),@MATB VARCHAR(10),@NGAYLAP DATETIME, @TONGTIEN FLOAT
AS 
  INSERT INTO HOADON VALUES(@MAHD,@MAKH,@MATB,@NGAYLAP,@TONGTIEN) 
---------  
GO
CREATE PROC PROC_UPDATE_HOADON @MAHD VARCHAR(10),@MAKH VARCHAR(10),@MATB VARCHAR(10),@NGAYLAP DATETIME, @TONGTIEN FLOAT
AS 
  UPDATE HOADON SET MAKH = @MAKH, MATB = @MATB,NGAYLAP =@NGAYLAP,TONGTIEN= @TONGTIEN WHERE  MAHD =@MAHD
---------
GO
CREATE PROC PROC_DELETE_HOADON @MAHD VARCHAR(10)
AS 
  DELETE HOADON WHERE MAHD = @MAHD

 ---------------6.PHIEUTHUE----------------



GO
CREATE PROC PROC_INSERT_PHIEUTHUE @MAPTHUE VARCHAR(10), @MATB VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @SOLUONG INT, @NGAYTHUE DATE, @NGAYHENTRA DATE, @TIENCOC FLOAT
AS 
  INSERT INTO PHIEUTHUETHIETBI VALUES(@MAPTHUE, @MATB, @MANV, @MAKH, @SOLUONG, @NGAYTHUE, @NGAYHENTRA, @TIENCOC) 
---------  
GO
CREATE PROC PROC_UPDATE_PHIEUTHUE @MAPTHUE VARCHAR(10), @MATB VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @SOLUONG INT, @NGAYTHUE DATE, @NGAYHENTRA DATE, @TIENCOC FLOAT
AS 
  UPDATE PHIEUTHUETHIETBI SET  MATB = @MATB,MAKH = @MAKH, MANV = @MANV, SOLUONG = @SOLUONG, NGAYHENTRA = @NGAYHENTRA, TIENCOC=@TIENCOC WHERE  MAPTHUE =@MAPTHUE
---------
GO
CREATE PROC PROC_DELETE_PHIEUTHUE @MAPTHUE VARCHAR(10)
AS 
  DELETE PHIEUTHUETHIETBI WHERE MAPTHUE = @MAPTHUE



-----SINHMATUDONGCHO NHANVIEN

GO
  CREATE PROC PROC_SINHMATUDONG_NV @PASS VARCHAR(50) ,@HOTEN NVARCHAR(35),@GIOITINH BIT,@SDT VARCHAR(15), @CHUCVU NVARCHAR(50), @EMAIL VARCHAR(50)
  AS
  DECLARE @NAM  VARCHAR(2)
  DECLARE @MA  VARCHAR(6)
  DECLARE @STT INT
  SET @NAM =  CAST(RIGHT(YEAR (GETDATE()),2) AS VARCHAR(2))
  DECLARE CUR CURSOR
  FOR SELECT MANV FROM  NHANVIEN  WHERE RIGHT(LEFT(MANV,4),2) =@NAM
  OPEN CUR
  SET @STT = 1
  FETCH NEXT FROM CUR INTO @MA
  WHILE @@FETCH_STATUS = 0
  BEGIN
  IF(CAST(RIGHT(@MA,2) AS INT) = @STT)
	SET @STT = @STT+1;
	ELSE BREAK;
	FETCH NEXT FROM CUR INTO @MA	
  END
	IF(@STT<10)	
		SET @MA = 'MF'+@NAM+'0'+CAST(@STT AS VARCHAR(2))
	 ELSE
		SET @MA = 'MF'+@NAM+CAST(@STT AS VARCHAR(2))
		EXEC  PROC_INSERT_NHANVIEN @MA, @PASS ,@HOTEN,@GIOITINH,@SDT, @CHUCVU, @EMAIL
	CLOSE CUR
	DEALLOCATE CUR
	
SELECT * FROM NHANVIEN



EXEC PROC_SINHMATUDONG_NV '123', N'Trần Hải Cường',1,'0839776655','QUANLY', 'xuantoannguyen2212@gmail.com'



-----SINHMATUDONGCHO HOA DON

GO
  CREATE PROC PROC_SINHMATUDONG_HD @MAKH VARCHAR(10),@MATB VARCHAR(10),@NGAYLAP DATETIME, @TONGTIEN FLOAT
  AS
  DECLARE @NAM  VARCHAR(2)
  DECLARE @MA  VARCHAR(6)
  DECLARE @STT INT
  SET @NAM =  CAST(RIGHT(YEAR (GETDATE()),2) AS VARCHAR(2))
  DECLARE CUR CURSOR
  FOR SELECT MAHD FROM  HOADON  WHERE RIGHT(LEFT(MAHD,4),2) =@NAM
  OPEN CUR
  SET @STT = 1
  FETCH NEXT FROM CUR INTO @MA
  WHILE @@FETCH_STATUS = 0
  BEGIN
  IF(CAST(RIGHT(@MA,2) AS INT) = @STT)
	SET @STT = @STT+1;
	ELSE BREAK;
	FETCH NEXT FROM CUR INTO @MA	
  END
	IF(@STT<10)	
		SET @MA = 'HD'+@NAM+'0'+CAST(@STT AS VARCHAR(2))
	 ELSE
		SET @MA = 'HD'+@NAM+CAST(@STT AS VARCHAR(2))
		EXEC PROC_INSERT_HOADON @MA,@MAKH, @MATB, @NGAYLAP, @TONGTIEN
	CLOSE CUR
	DEALLOCATE CUR
	
SELECT * FROM HOADON



-----SINHMATUDONGCHO KHACH HANG

GO
  CREATE PROC PROC_SINHMATUDONG_KH @TENKH NVARCHAR(35),@DIACHI NVARCHAR(100),@SDT VARCHAR(15), @EMAIL VARCHAR(50)
  AS
  DECLARE @NAM  VARCHAR(2)
  DECLARE @MA  VARCHAR(6)
  DECLARE @STT INT
  SET @NAM =  CAST(RIGHT(YEAR (GETDATE()),2) AS VARCHAR(2))
  DECLARE CUR CURSOR
  FOR SELECT MAKH FROM  KHACHHANG  WHERE RIGHT(LEFT(MAKH,4),2) =@NAM
  OPEN CUR
  SET @STT = 1
  FETCH NEXT FROM CUR INTO @MA
  WHILE @@FETCH_STATUS = 0
  BEGIN
  IF(CAST(RIGHT(@MA,2) AS INT) = @STT)
	SET @STT = @STT+1;
	ELSE BREAK;
	FETCH NEXT FROM CUR INTO @MA	
  END
	IF(@STT<10)	
		SET @MA = 'KH'+@NAM+'0'+CAST(@STT AS VARCHAR(2))
	 ELSE
		SET @MA = 'KH'+@NAM+CAST(@STT AS VARCHAR(2))
		EXEC  PROC_INSERT_KHACHHANG @MA,@TENKH,@DIACHI,@SDT, @EMAIL
	CLOSE CUR
	DEALLOCATE CUR
	
SELECT * FROM KHACHHANG

-----SINHMATUDONGCHO THIETBI

GO
  CREATE PROC PROC_SINHMATUDONG_TB @MATB VARCHAR(10),@TENTB NVARCHAR(50), @SOLUONG INT, @MOTA NVARCHAR(50), @TINHTRANG NVARCHAR(50), @GIATRITB FLOAT, @GIATHUE FLOAT, @MALOAI VARCHAR(10)
  AS
  DECLARE @NAM  VARCHAR(2)
  DECLARE @MA  VARCHAR(6)
  DECLARE @STT INT
  SET @NAM =  CAST(RIGHT(YEAR (GETDATE()),2) AS VARCHAR(2))
  DECLARE CUR CURSOR
  FOR SELECT MATB FROM  THIETBI  WHERE RIGHT(LEFT(MATB,4),2) =@NAM
  OPEN CUR
  SET @STT = 1
  FETCH NEXT FROM CUR INTO @MA
  WHILE @@FETCH_STATUS = 0
  BEGIN
  IF(CAST(RIGHT(@MA,2) AS INT) = @STT)
	SET @STT = @STT+1;
	ELSE BREAK;
	FETCH NEXT FROM CUR INTO @MA	
  END
	IF(@STT<10)	
		SET @MA = 'TB'+@NAM+'0'+CAST(@STT AS VARCHAR(2))
	 ELSE
		SET @MA = 'TB'+@NAM+CAST(@STT AS VARCHAR(2))
		EXEC  PROC_INSERT_THIETBI @MA, @TENTB, @SOLUONG, @MOTA, @TINHTRANG, @GIATRITB, @GIATHUE, @MALOAI
	CLOSE CUR
	DEALLOCATE CUR
	
SELECT * FROM THIETBI

-----SINHMATUDONGCHO MAPHIEUTHUE

GO
  CREATE PROC PROC_SINHMATUDONG_PT @MATB VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @SOLUONG INT, @NGAYTHUE DATE, @NGAYHENTRA DATE, @TIENCOC FLOAT
  AS
  DECLARE @NAM  VARCHAR(2)
  DECLARE @MA  VARCHAR(6)
  DECLARE @STT INT
  SET @NAM =  CAST(RIGHT(YEAR (GETDATE()),2) AS VARCHAR(2))
  DECLARE CUR CURSOR
  FOR SELECT MAPTHUE FROM  PHIEUTHUETHIETBI  WHERE RIGHT(LEFT(MAPTHUE,4),2) =@NAM
  OPEN CUR
  SET @STT = 1
  FETCH NEXT FROM CUR INTO @MA
  WHILE @@FETCH_STATUS = 0
  BEGIN
  IF(CAST(RIGHT(@MA,2) AS INT) = @STT)
	SET @STT = @STT+1;
	ELSE BREAK;
	FETCH NEXT FROM CUR INTO @MA	
  END
	IF(@STT<10)	
		SET @MA = 'PT'+@NAM+'0'+CAST(@STT AS VARCHAR(2))
	 ELSE
		SET @MA = 'PT'+@NAM+CAST(@STT AS VARCHAR(2))
		EXEC  PROC_INSERT_PHIEUTHUE @MA, @MATB, @MANV, @MAKH, @SOLUONG, @NGAYTHUE, @NGAYHENTRA, @TIENCOC
	CLOSE CUR
	DEALLOCATE CUR
	
SELECT * FROM NHANVIEN

--//khi nhap PHIEU THUE THIET BI vao thi giam so luong THIET BI
select * from PHIEUTHUETHIETBI
create trigger THUETHIETBI
on PHIEUTHUETHIETBI
for  insert
as
declare @MATB varchar(10),@SOLUONG int,@SoLuongcu int
select @MATB =MATB, @SOLUONG = SOLUONG from inserted
update @S


