CREATE DATABASE QLTHIETBISTUDIO
GO

USE QLTHIETBISTUDIO
GO
 

CREATE TABLE CHUCNANG
(
	MaCN CHAR(5) PRIMARY KEY,
	TenCN NVARCHAR(35) NOT NULL,
	MoTaCN NVARCHAR(50) NOT NULL
)
GO


CREATE TABLE NGUOIDUNG
(
	MaNV CHAR(5) PRIMARY KEY,  -- ma nv bat dau la MF*****, tự động radom k trùng
	TaiKhoan VARCHAR(30) NOT NULL, -- Tiếng anh k dấu, không cách
	MatKhau VARCHAR(100) NOT NULL, -- ràng buộc >8 ký tự, nhỏ hơn 100
	HoTen NVARCHAR(35) NOT NULL,
	GioiTinh BIT DEFAULT 0, -- 1 LÀ NAM 0 LÀ NỮ --- Them Gioi tinh khac
	SDT VARCHAR(15) NOT NULL, -- Ràng buộc SDT
	Email VARCHAR(50) NOT NULL, -- Ràng buộc Email
	ChucDanh NVARCHAR(30) NOT NULL, -- NHÂN VIÊN HOẶC QUẢN LÝ
	MaCN CHAR(5) NOT NULL 
	FOREIGN KEY (MaCN) REFERENCES dbo.CHUCNANG(MaCN)
)
GO


CREATE TABLE LOAITHIETBI
(
	LoaiTB CHAR(5) PRIMARY KEY, -- Sai Ten
	TenLoai NVARCHAR(35) NOT NULL,
	MoTaLoaiTB NVARCHAR(50) NOT NULL
)
GO


CREATE TABLE THIETBI
(
	MaTB CHAR(5) PRIMARY KEY, 
	TenTB NVARCHAR(35) NOT NULL,
	MoTaTB NVARCHAR(50) NOT NULL,
	TinhTrangTB NVARCHAR(50) NOT NULL,
	LoaiTB CHAR(5) NOT NULL

	FOREIGN KEY (LoaiTB) REFERENCES dbo.LOAITHIETBI(LoaiTB)
)
GO

CREATE TABLE KHACHHANG
(
	MaKH CHAR(5) PRIMARY KEY,
	HoTen NVARCHAR(35) NOT NULL,
	GioiTinh BIT DEFAULT 0, -- 1 la nam 0 la nu
	SDT VARCHAR(15) NOT NULL,
	DiaChi NVARCHAR(50)
)
GO


CREATE TABLE PHIEUTHUETHIETBI
(
	MaPTHUE CHAR(5) PRIMARY KEY,
	SLThietBiThue INT NOT NULL,
	NgayThue DATE NOT NULL,
	NgayTra DATE NOT NULL,
	SoGioThue FLOAT NOT NULL,
	TienCoc INT NOT NULL,
	NoiDungPhieuThue NVARCHAR(50),
	NguoiChoThue NVARCHAR(35) NOT NULL,
	NguoiThue NVARCHAR(35) NOT NULL,
	MaKH CHAR(5) NOT NULL,
	MaNV CHAR(5) NOT NULL,
	MaTB CHAR(5) NOT NULL

	FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(MaKH),
	FOREIGN KEY (MaNV) REFERENCES dbo.NGUOIDUNG(MaNV),
	FOREIGN KEY (MaTB) REFERENCES dbo.THIETBI(MaTB)
)
GO
 

CREATE TABLE HOADON
(
	MaHD CHAR(5) PRIMARY KEY,
	NgayLap DATE NOT NULL,
	TrangThaiHD BIT DEFAULT 0, -- 1 THANH TOÁN RỒI 0 CHƯA THANH TOÁN
	GhiNho NVARCHAR(50) NOT NULL,
	NguoiLap NVARCHAR(35) NOT NULL,
	NguoiTra NVARCHAR(35) NOT NULL,
	MaNV CHAR(5) NOT NULL,
	MaPTHUE CHAR(5) NOT NULL

	FOREIGN KEY (MaNV) REFERENCES dbo.NGUOIDUNG(MaNV),
	FOREIGN KEY (MaPTHUE) REFERENCES dbo.PHIEUTHUETHIETBI(MaPTHUE)
)
GO

CREATE TABLE CTHOADON
(
	MaCTHD CHAR(5) PRIMARY KEY,
	TongTien INT NOT NULL,
	TienDenBu INT, -- NẾU CÓ
	NoiDungHD NVARCHAR(50), -- NẾU CÓ
	MaHD CHAR(5) NOT NULL

	FOREIGN KEY (MaHD) REFERENCES dbo.HOADON(MaHD)
)
GO

